### ISSUE TITLE
Discuss future direction of Perl::Critic

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#713]
@petdance and @wbraswell are both very interested in keeping Perl::Critic going.  @wbraswell sounds like he has more time to put toward it than I do.

What do we need to do to keep Perl::Critic going?

**Comment by wbraswell** [comment]
Yes I'm here and actively working on Perl::Critic bugs right this moment, it so happens.  :-)

@thaljef Please set @petdance and I as "owners" in the GitHub Perl-Critic org and give us both co-maint for CPAN, we will work together to make sure Perl::Critic stays alive and well!

https://github.com/orgs/Perl-Critic/people

**Comment by petdance** [comment]
Here's a braindump of thoughts:

* We have a lot of stale branches.  Let's look at getting rid of them, so that we can...
* Start a `dev` branch and make it the defaults so we're not working on `master`, but first we'll have to ....
* Go through existing PRs and apply what we can to master, because switching to the dev branch will make existing PRs take some more work.
* Establish a process for how things get applied and updated.  For instance, on my projects I don't apply any changes from the outside without immediately thanking the contributor in the changelog.  With one person running a project, then that's not a problem.  With more than that, then you need to make sure you know what's what.  Same thing with workflow + branches etc.
* Go through existing issues and label them, after setting up a bunch of labels.  At the very least look at labels like "bug", "enhancement", "documentation".
* Close the issues that we aren't going to deal with.  273 open issues is a daunting number to deal with, and it makes people think that nothing's getting done on the project.

Those are my initial thoughts.  What else would you add, @wbraswell?  Anything in there you disagree with?

**Comment by wbraswell** [comment]
Before reading the braindump...
I have revived and registered the official IRC channel, complete with a real topic and ilbot2 public IRC logging (thanks to moritz)...
https://irclog.perlgeek.de/perlcritic/

irc.perl.org
#perlcritic
willthechill

**Comment by wbraswell** [comment]
@petdance 
Okay I read your braindump, I am in agreement with all items!

**Comment by petdance** [comment]
> irc://irc.perl.org/#perlcritic

I won't be hanging around in IRC.

**Comment by petdance** [comment]
We'll want to talk to @dolmen to see if his `dev` branch can get deleted so we can start a new one.

https://github.com/Perl-Critic/Perl-Critic/tree/dev

**Comment by thaljef** [comment]
Done. @petdance and @wbraswell are now owners of the Perl::Critic organization.

**Comment by wbraswell** [comment]
@thaljef 
Awesome, thanks!  :+1: 

@petdance 
Okay I will be the point-man for IRC.
I will wait until you give further feedback about the dev branch issue.

**Comment by petdance** [comment]
> Done. @petdance and @wbraswell are now owners of the Perl::Critic organization.

We won't let you down, sir!  Thanks for all that you've put into such an important tool.

**Comment by petdance** [comment]
We also need to document the build process.  I know the one time I tried to release P::C I got very lost.

**Comment by wbraswell** [comment]
@petdance 
Yes I agree about documenting the release process, personally I've only ever used EU::MM for my CPAN distribution releases...
Also!
Apparently we have both Travis-CI and IRC build reporting enabled, I just got a surprise message from the bot:
"dev: The build is still failing. https://travis-ci.org/Perl-Critic/Perl-Critic/builds/189332789"

**Comment by wbraswell** [comment]
@petdance 
I assume you are somehow keeping track of all the pull requests which you are currently merging, so that we can include all the required info in the Changes file and/or docs?  (I haven't even looked at any of the pull requests myself.)

**Comment by thaljef** [comment]
The PAUSE permissions are a little more complicated. All the P::C namespaces are owned by `CRITICRE` which is some kind of group account. I'll have to ask @andk how to add you guys to that.

**Comment by wbraswell** [comment]
@thaljef  Wow I've never even heard of a group PAUSE account!

**Comment by petdance** [comment]
> I assume you are somehow keeping track of all the pull requests

No, I was not, because they've all been documentation fixes, mostly typos.  No functional changes that would go into the changelog. 

I knocked those four doc PRs out so we can look at functionality that we need to look at.

**Comment by wbraswell** [comment]
@petdance 
Ah okay, that makes sense, great!

**Comment by moregan** [comment]
I hope to again be a good go-between between P::C and PPI when I get back into PPI some time this year.

**Comment by petdance** [comment]
@moregan What is the state of PPI?  Is it still in active development?

**Comment by moregan** [comment]
I'd say PPI is in a holding patter, having seen little activity over the last two years. Most of the work in the last several years has been small improvements and fixes.

**Comment by wbraswell** [comment]
@thaljef 
Looking through the pause.cpan.org web interface, I can't find any info about the CRITICRE group?
Also, looking through the MetaCPAN user interface, I see both CRITICRE and PETDANCE (among others) in the permissions list, but not my WBRASWELL user?
https://metacpan.org/permission/distribution/Perl-Critic
